services:
  api:
    build:
      context: ./
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - api_data:/app/static
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      API_BASE_URL: ${API_BASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORDS_SALT_SECRET_KEY: ${PASSWORDS_SALT_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_USE_TLS: ${SMTP_USE_TLS}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      ENV: ${ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_TRACES_SAMPLE_RATE: ${SENTRY_TRACES_SAMPLE_RATE}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
      METRICS_TOKEN: ${METRICS_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      FLAGSMITH_TOKEN: ${FLAGSMITH_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  api_data:
  redis_data:
